### ISSUE TITLE
Mac OS X Mavericks, problem with nc -l -p 

### ISSUE THREAD

**Issue by moolah-ecommerce** [2creatives/vagrant-centos#5]
Cannot combine these under Mac OS X.  Not sure if this is a change.  works as sh ./http.sh nc -l 8081

**Comment by casr** [comment]
I originally had it with the `-p` switch thinking that the `netcat` version that shipped with Macports was more modern and therefore more likely to be available cross platform. Turns out that it's actually an older implementation!

Anyway it appears I was wrong about this so I'm going to favour the command above in future and hope that it pleases more people. Thanks for the report!

**Comment by casr** [comment]
2d5c3ab9e0e64b3b185ca0d4a2b81b3c760e1d9a
